name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: kivy/buildozer:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix Git Directory Permissions
        run: |
          git config --global --add safe.directory '*'

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk
